version: "3.9"

# 서버 환경에서는 네트워크를 명시적으로 정의할 필요가 거의 없습니다.
# Docker Compose가 기본적으로 서비스를 위한 네트워크를 생성해 줍니다.

services:
  main_backend:
    # ❗️ build 대신 image를 사용합니다.
    # CI/CD 파이프라인이 Docker Hub에 푸시할 이미지의 주소입니다.
    image: tjdqls3607/gurumate-main-backend:latest
    container_name: GuruMate_main_backend
    restart: always
    ports:
      - "8080:8080"
    # ❗️ environment 블록 대신 env_file을 사용합니다.
    # CI/CD 파이프라인이 EC2 서버에 동적으로 생성해 줄 .env 파일로부터
    # RDS 접속 정보 등 모든 환경변수를 안전하게 읽어옵니다.
    env_file:
      - ./.env

  main_frontend:
    # ❗️ 프론트엔드도 build 대신 image를 사용합니다.
    image: tjdqls3607/gurumate-main-frontend:latest
    container_name: GuruMate_main_frontend
    restart: always
    ports:
      # ❗️ 프론트엔드는 보통 80 포트를 사용하여 IP 주소만으로 접속하게 합니다.
      - "80:80"
    depends_on:
      - main_backend

# ❗️ db_data 볼륨은 더 이상 필요 없으므로 제거합니다.