version: "3.9"

services:
  db:
    image: postgres:16
    container_name: GuruMate_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: gurumate
      POSTGRES_PASSWORD: gurumate_pw
      POSTGRES_DB: gurumate
      TZ: Asia/Seoul
    ports:
      - "5433:5432"                       # 호스트 5433 사용 권장(충돌 방지)
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d  # 최초 스키마/확장 자동 실행
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gurumate -d gurumate -h 127.0.0.1 -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 10

  main_backend:
    build: ../GuruMate_main_backend
    container_name: GuruMate_main_backend
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/gurumate  # 컨테이너간 호스트명은 서비스명(db)
      SPRING_DATASOURCE_USERNAME: gurumate
      SPRING_DATASOURCE_PASSWORD: gurumate_pw
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

#  admin_backend:
#    build: ./admin-backend
#    container_name: GuruMate_admin_backend
#    restart: unless-stopped
#    environment:
#      SPRING_PROFILES_ACTIVE: dev
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/gurumate
#      SPRING_DATASOURCE_USERNAME: gurumate
#      SPRING_DATASOURCE_PASSWORD: gurumate_pw
#    ports:
#      - "8081:8080"
#    depends_on:
#      db:
#        condition: service_healthy
#
#  main_frontend:
#    build: ./main-frontend
#    container_name: GuruMate_main_frontend
#    restart: unless-stopped
#    ports:
#      - "3000:3000"
#    depends_on:
#      - main_backend

volumes:
  db_data:
